package moe.clienthax.pixelmonbridge.api.block;

import org.spongepowered.api.block.BlockType;
import org.spongepowered.api.util.generator.dummy.DummyObjectProvider;

/**
 * Created by clienthax on 12/03/2018.
 */
public class PixelmonBlockTypes {
    //TODO Not sure if this will explode, in theory it shouldnt be called until pixelmon is 'alive'

    //TODO What if blocks are removed / added inbetween versions? .get isnt exactly safe

    public static final BlockType PINK_VENDING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLUE_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TIMED_FALL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TEMPLE_STAIRS = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType FOSSIL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType YELLOW_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TRADE_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TV = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GRACIDEABLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType MECHANICAL_ANVIL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType STICK_PLATE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType DAWN_DUSK_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_CHARTI = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_SHUCA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType CRYSTAL_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_APICOT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SHINGLES = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GREEN_VENDING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_JABOCA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_ENIGMA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BRAILLE_BLOCK2 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType INSIDE_WALL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType MOLTRES_SHRINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType FOSSIL_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RED_CUSHION_CHAIR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PC = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BAUXITE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_SIDE3 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_SIDE2 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_SIDE1 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType LEAF_STONE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_SIDE4 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType INSIDE_WALL_MOLDING = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_HABAN = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType MOSS_ROCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_GIFT_EVENT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ZAPDOS_SHRINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_GREPA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BRIDGE_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_LANSAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RUBY_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_CHEST = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TEMPLE_BRICK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType YELLOW_UMBRELLA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKEMART_SIGN = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RUBY_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TEMPLE_BRICK_STAIRS = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_CORNER2 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_CORNER3 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RED_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_CORNER4 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND_CORNER1 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType CAVE_ROCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PINK_CLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TIMESPACE_ALTAR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TEMPLE_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_QUALOT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_KASIB = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RED_VENDING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BOLDER = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType CHAIR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ELEVATOR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType AMETHYST_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_BABIRI = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GYM_SIGN = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType END_TABLE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_HONDEW = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType UNOWN_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PICKET_FENCE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SANDY_GRASS = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType HEALER = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_TAMATO = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLUE_VENDING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RED_UMBRELLA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ORANGE_VENDING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SAPPHIRE_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_SAND = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType MOVEMENT_PLATE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_PETAYA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType CRYSTAL_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLUE_RUG = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType FOSSIL_CLEANER = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType HIDDEN_WOODEN_DOOR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType YELLOW_RUG = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ICE_ROCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType MASTER_CHEST = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_GIFT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TREE_TOP = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLUE_UMBRELLA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType DUSTY_RUINS_WALL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType FRIDGE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_POMEG = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RANCH = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GREEN_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GREEN_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RED_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TEMPLE_PILLAR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RUINS_WALL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType HIDDEN_CUBE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BOX = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType HIDDEN_IRON_DOOR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_LIECHI = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLUE_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKECENTER_SIGN = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType YELLOW_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_ROWAP = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SUN_STONE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SILICON_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SPAWNER_CAVE_ROCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType RED_RUG = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType YELLOW_VENDING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_CHERI = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_GANLON = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_KELPSY = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType CLOTHED_TABLE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType THUNDER_STONE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_RINDO = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType WARP_PLATE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType WATER_STONE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType UNOWN_BLOCK2 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType WOODEN_FLOORING = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType WINDOW1 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_PASSHO = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_DIRT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType WINDOW2 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_MICLE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TRASH_CAN = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType AMETHYST_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_YACHE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_CUSTAP = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType HIDDEN_PRESSURE_PLATE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType OUTSIDE_WALL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_STARF = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PIXELMON_GRASS = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_CHOPLE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ORANGE_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SAPPHIRE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType CLONING_MACHINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType YELLOW_CUSHION_CHAIR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PURPLE_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType WHITE_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GREEN_FOLDING_CHAIR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_OCCA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ANVIL = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PINK_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PINK_WATER_FLOAT = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GREEN_RUG = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_TANGA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ULTRA_CHEST = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType POKE_GRASS = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_COLBUR = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType FOSSIL_DISPLAY = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ROCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType FIRE_STONE_ORE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLACK_APRICORN_TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SHINGLES_CORNER1 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType SHINGLES_CORNER2 = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType GREEN_UMBRELLA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_KEBIA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_WACAN = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_SALAC = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType ARTICUNO_SHRINE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BERRYTREE_COBA = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TREE_BOTTOM = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType PIXELMON_SPAWNER = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType TREE = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BLUE_CLOCK = DummyObjectProvider.createFor(BlockType.class, "");
    public static final BlockType BRAILLE_BLOCK = DummyObjectProvider.createFor(BlockType.class, "");

    private PixelmonBlockTypes() {
        throw new AssertionError("You should not be attempting to instantiate this class.");
    }
}
