package moe.clienthax.pixelmonbridge.api.block;

import org.spongepowered.api.Sponge;
import org.spongepowered.api.block.BlockType;

/**
 * Created by clienthax on 12/03/2018.
 */
public class PixelmonBlockTypes {
    //TODO Not sure if this will explode, in theory it shouldnt be called until pixelmon is 'alive'

    //TODO What if blocks are removed / added inbetween versions? .get isnt exactly safe

    public static final BlockType PINK_VENDING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pink_vending_machine").get();
    public static final BlockType BLUE_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:blue_water_float").get();
    public static final BlockType TIMED_FALL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:timed_fall").get();
    public static final BlockType TEMPLE_STAIRS = Sponge.getRegistry().getType(BlockType.class, "pixelmon:temple_stairs").get();
    public static final BlockType FOSSIL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:fossil").get();
    public static final BlockType YELLOW_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:yellow_apricorn_tree").get();
    public static final BlockType TRADE_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:trade_machine").get();
    public static final BlockType TV = Sponge.getRegistry().getType(BlockType.class, "pixelmon:tv").get();
    public static final BlockType GRACIDEABLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:gracideablock").get();
    public static final BlockType MECHANICAL_ANVIL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:mechanical_anvil").get();
    public static final BlockType STICK_PLATE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:stick_plate").get();
    public static final BlockType DAWN_DUSK_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:dawn_dusk_ore").get();
    public static final BlockType BERRYTREE_CHARTI = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_charti").get();
    public static final BlockType BERRYTREE_SHUCA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_shuca").get();
    public static final BlockType CRYSTAL_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:crystal_block").get();
    public static final BlockType BERRYTREE_APICOT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_apicot").get();
    public static final BlockType SHINGLES = Sponge.getRegistry().getType(BlockType.class, "pixelmon:shingles").get();
    public static final BlockType GREEN_VENDING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:green_vending_machine").get();
    public static final BlockType BERRYTREE_JABOCA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_jaboca").get();
    public static final BlockType BERRYTREE_ENIGMA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_enigma").get();
    public static final BlockType BRAILLE_BLOCK2 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:braille_block2").get();
    public static final BlockType INSIDE_WALL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:inside_wall").get();
    public static final BlockType MOLTRES_SHRINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:moltres_shrine").get();
    public static final BlockType FOSSIL_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:fossil_machine").get();
    public static final BlockType RED_CUSHION_CHAIR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:red_cushion_chair").get();
    public static final BlockType PC = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pc").get();
    public static final BlockType BAUXITE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:bauxite_ore").get();
    public static final BlockType POKE_SAND_SIDE3 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_side3").get();
    public static final BlockType POKE_SAND_SIDE2 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_side2").get();
    public static final BlockType POKE_SAND_SIDE1 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_side1").get();
    public static final BlockType LEAF_STONE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:leaf_stone_ore").get();
    public static final BlockType POKE_SAND_SIDE4 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_side4").get();
    public static final BlockType INSIDE_WALL_MOLDING = Sponge.getRegistry().getType(BlockType.class, "pixelmon:inside_wall_molding").get();
    public static final BlockType BERRYTREE_HABAN = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_haban").get();
    public static final BlockType MOSS_ROCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:moss_rock").get();
    public static final BlockType POKE_GIFT_EVENT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_gift_event").get();
    public static final BlockType ZAPDOS_SHRINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:zapdos_shrine").get();
    public static final BlockType BERRYTREE_GREPA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_grepa").get();
    public static final BlockType BRIDGE_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:bridge_block").get();
    public static final BlockType BERRYTREE_LANSAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_lansat").get();
    public static final BlockType RUBY_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:ruby_ore").get();
    public static final BlockType POKE_CHEST = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_chest").get();
    public static final BlockType TEMPLE_BRICK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:temple_brick").get();
    public static final BlockType YELLOW_UMBRELLA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:yellow_umbrella").get();
    public static final BlockType POKEMART_SIGN = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pokemart_sign").get();
    public static final BlockType RUBY_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:ruby_block").get();
    public static final BlockType TEMPLE_BRICK_STAIRS = Sponge.getRegistry().getType(BlockType.class, "pixelmon:temple_brick_stairs").get();
    public static final BlockType POKE_SAND_CORNER2 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_corner2").get();
    public static final BlockType POKE_SAND_CORNER3 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_corner3").get();
    public static final BlockType RED_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:red_water_float").get();
    public static final BlockType POKE_SAND_CORNER4 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_corner4").get();
    public static final BlockType POKE_SAND_CORNER1 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand_corner1").get();
    public static final BlockType CAVE_ROCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:cave_rock").get();
    public static final BlockType PINK_CLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pink_clock").get();
    public static final BlockType TIMESPACE_ALTAR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:timespace_altar").get();
    public static final BlockType TEMPLE_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:temple_block").get();
    public static final BlockType BERRYTREE_QUALOT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_qualot").get();
    public static final BlockType BERRYTREE_KASIB = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_kasib").get();
    public static final BlockType RED_VENDING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:red_vending_machine").get();
    public static final BlockType BOLDER = Sponge.getRegistry().getType(BlockType.class, "pixelmon:bolder").get();
    public static final BlockType CHAIR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:chair").get();
    public static final BlockType ELEVATOR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:elevator").get();
    public static final BlockType AMETHYST_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:amethyst_block").get();
    public static final BlockType BERRYTREE_BABIRI = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_babiri").get();
    public static final BlockType GYM_SIGN = Sponge.getRegistry().getType(BlockType.class, "pixelmon:gym_sign").get();
    public static final BlockType END_TABLE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:end_table").get();
    public static final BlockType BERRYTREE_HONDEW = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_hondew").get();
    public static final BlockType UNOWN_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:unown_block").get();
    public static final BlockType PICKET_FENCE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:picket_fence").get();
    public static final BlockType SANDY_GRASS = Sponge.getRegistry().getType(BlockType.class, "pixelmon:sandy_grass").get();
    public static final BlockType HEALER = Sponge.getRegistry().getType(BlockType.class, "pixelmon:healer").get();
    public static final BlockType BERRYTREE_TAMATO = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_tamato").get();
    public static final BlockType BLUE_VENDING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:blue_vending_machine").get();
    public static final BlockType RED_UMBRELLA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:red_umbrella").get();
    public static final BlockType ORANGE_VENDING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:orange_vending_machine").get();
    public static final BlockType SAPPHIRE_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:sapphire_block").get();
    public static final BlockType POKE_SAND = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_sand").get();
    public static final BlockType MOVEMENT_PLATE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:movement_plate").get();
    public static final BlockType BERRYTREE_PETAYA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_petaya").get();
    public static final BlockType CRYSTAL_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:crystal_ore").get();
    public static final BlockType BLUE_RUG = Sponge.getRegistry().getType(BlockType.class, "pixelmon:blue_rug").get();
    public static final BlockType FOSSIL_CLEANER = Sponge.getRegistry().getType(BlockType.class, "pixelmon:fossil_cleaner").get();
    public static final BlockType HIDDEN_WOODEN_DOOR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:hidden_wooden_door").get();
    public static final BlockType YELLOW_RUG = Sponge.getRegistry().getType(BlockType.class, "pixelmon:yellow_rug").get();
    public static final BlockType ICE_ROCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:ice_rock").get();
    public static final BlockType MASTER_CHEST = Sponge.getRegistry().getType(BlockType.class, "pixelmon:master_chest").get();
    public static final BlockType POKE_GIFT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_gift").get();
    public static final BlockType TREE_TOP = Sponge.getRegistry().getType(BlockType.class, "pixelmon:tree_top").get();
    public static final BlockType BLUE_UMBRELLA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:blue_umbrella").get();
    public static final BlockType DUSTY_RUINS_WALL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:dusty_ruins_wall").get();
    public static final BlockType FRIDGE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:fridge").get();
    public static final BlockType BERRYTREE_POMEG = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_pomeg").get();
    public static final BlockType RANCH = Sponge.getRegistry().getType(BlockType.class, "pixelmon:ranch").get();
    public static final BlockType GREEN_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:green_apricorn_tree").get();
    public static final BlockType GREEN_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:green_water_float").get();
    public static final BlockType RED_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:red_apricorn_tree").get();
    public static final BlockType TEMPLE_PILLAR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:temple_pillar").get();
    public static final BlockType RUINS_WALL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:ruins_wall").get();
    public static final BlockType HIDDEN_CUBE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:hidden_cube").get();
    public static final BlockType BOX = Sponge.getRegistry().getType(BlockType.class, "pixelmon:box").get();
    public static final BlockType HIDDEN_IRON_DOOR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:hidden_iron_door").get();
    public static final BlockType BERRYTREE_LIECHI = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_liechi").get();
    public static final BlockType BLUE_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:blue_apricorn_tree").get();
    public static final BlockType POKECENTER_SIGN = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pokecenter_sign").get();
    public static final BlockType YELLOW_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:yellow_water_float").get();
    public static final BlockType BERRYTREE_ROWAP = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_rowap").get();
    public static final BlockType SUN_STONE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:sun_stone_ore").get();
    public static final BlockType SILICON_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:silicon_ore").get();
    public static final BlockType SPAWNER_CAVE_ROCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:spawner_cave_rock").get();
    public static final BlockType RED_RUG = Sponge.getRegistry().getType(BlockType.class, "pixelmon:red_rug").get();
    public static final BlockType YELLOW_VENDING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:yellow_vending_machine").get();
    public static final BlockType BERRYTREE_CHERI = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_cheri").get();
    public static final BlockType BERRYTREE_GANLON = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_ganlon").get();
    public static final BlockType BERRYTREE_KELPSY = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_kelpsy").get();
    public static final BlockType CLOTHED_TABLE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:clothed_table").get();
    public static final BlockType THUNDER_STONE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:thunder_stone_ore").get();
    public static final BlockType BERRYTREE_RINDO = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_rindo").get();
    public static final BlockType WARP_PLATE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:warp_plate").get();
    public static final BlockType WATER_STONE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:water_stone_ore").get();
    public static final BlockType UNOWN_BLOCK2 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:unown_block2").get();
    public static final BlockType WOODEN_FLOORING = Sponge.getRegistry().getType(BlockType.class, "pixelmon:wooden_flooring").get();
    public static final BlockType WINDOW1 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:window1").get();
    public static final BlockType BERRYTREE_PASSHO = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_passho").get();
    public static final BlockType POKE_DIRT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_dirt").get();
    public static final BlockType WINDOW2 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:window2").get();
    public static final BlockType BERRYTREE_MICLE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_micle").get();
    public static final BlockType TRASH_CAN = Sponge.getRegistry().getType(BlockType.class, "pixelmon:trash_can").get();
    public static final BlockType AMETHYST_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:amethyst_ore").get();
    public static final BlockType BERRYTREE_YACHE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_yache").get();
    public static final BlockType BERRYTREE_CUSTAP = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_custap").get();
    public static final BlockType HIDDEN_PRESSURE_PLATE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:hidden_pressure_plate").get();
    public static final BlockType OUTSIDE_WALL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:outside_wall").get();
    public static final BlockType BERRYTREE_STARF = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_starf").get();
    public static final BlockType PIXELMON_GRASS = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pixelmon_grass").get();
    public static final BlockType BERRYTREE_CHOPLE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_chople").get();
    public static final BlockType ORANGE_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:orange_water_float").get();
    public static final BlockType SAPPHIRE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:sapphire_ore").get();
    public static final BlockType CLONING_MACHINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:cloning_machine").get();
    public static final BlockType YELLOW_CUSHION_CHAIR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:yellow_cushion_chair").get();
    public static final BlockType PURPLE_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:purple_water_float").get();
    public static final BlockType WHITE_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:white_apricorn_tree").get();
    public static final BlockType GREEN_FOLDING_CHAIR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:green_folding_chair").get();
    public static final BlockType BERRYTREE_OCCA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_occa").get();
    public static final BlockType ANVIL = Sponge.getRegistry().getType(BlockType.class, "pixelmon:anvil").get();
    public static final BlockType PINK_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pink_apricorn_tree").get();
    public static final BlockType PINK_WATER_FLOAT = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pink_water_float").get();
    public static final BlockType GREEN_RUG = Sponge.getRegistry().getType(BlockType.class, "pixelmon:green_rug").get();
    public static final BlockType BERRYTREE_TANGA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_tanga").get();
    public static final BlockType ULTRA_CHEST = Sponge.getRegistry().getType(BlockType.class, "pixelmon:ultra_chest").get();
    public static final BlockType POKE_GRASS = Sponge.getRegistry().getType(BlockType.class, "pixelmon:poke_grass").get();
    public static final BlockType BERRYTREE_COLBUR = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_colbur").get();
    public static final BlockType FOSSIL_DISPLAY = Sponge.getRegistry().getType(BlockType.class, "pixelmon:fossil_display").get();
    public static final BlockType ROCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:rock").get();
    public static final BlockType FIRE_STONE_ORE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:fire_stone_ore").get();
    public static final BlockType BLACK_APRICORN_TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:black_apricorn_tree").get();
    public static final BlockType SHINGLES_CORNER1 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:shingles_corner1").get();
    public static final BlockType SHINGLES_CORNER2 = Sponge.getRegistry().getType(BlockType.class, "pixelmon:shingles_corner2").get();
    public static final BlockType GREEN_UMBRELLA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:green_umbrella").get();
    public static final BlockType BERRYTREE_KEBIA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_kebia").get();
    public static final BlockType BERRYTREE_WACAN = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_wacan").get();
    public static final BlockType BERRYTREE_SALAC = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_salac").get();
    public static final BlockType ARTICUNO_SHRINE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:articuno_shrine").get();
    public static final BlockType BERRYTREE_COBA = Sponge.getRegistry().getType(BlockType.class, "pixelmon:berrytree_coba").get();
    public static final BlockType TREE_BOTTOM = Sponge.getRegistry().getType(BlockType.class, "pixelmon:tree_bottom").get();
    public static final BlockType PIXELMON_SPAWNER = Sponge.getRegistry().getType(BlockType.class, "pixelmon:pixelmon_spawner").get();
    public static final BlockType TREE = Sponge.getRegistry().getType(BlockType.class, "pixelmon:tree").get();
    public static final BlockType BLUE_CLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:blue_clock").get();
    public static final BlockType BRAILLE_BLOCK = Sponge.getRegistry().getType(BlockType.class, "pixelmon:braille_block").get();

    private PixelmonBlockTypes() {
        throw new AssertionError("You should not be attempting to instantiate this class.");
    }


}
